[package]
name = "collect"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
libactions = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
discogs-rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
walkdir = { workspace = true }
